# GitHub Dependabot configuration file

version: 2
updates:

  # Maintain dependencies for GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"

  # Maintain dependencies for maven
  - package-ecosystem: "maven"
    directory: "/"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 20
    ignore:
      - dependency-name: "biz.aQute.bnd:biz.aQute.bndlib"
        versions:
          - ">=7.0.0" # does not support java 8
      - dependency-name: "biz.aQute.bnd:bnd-indexer-maven-plugin"
        versions:
          - ">=7.0.0" # does not support java 8
      - dependency-name: "biz.aQute.bnd:bnd-maven-plugin"
        versions:
          - ">=7.0.0" # does not support java 8
      - dependency-name: "jakarta.annotation:jakarta.annotation-api"
        versions:
          - ">=3.0.0" # does not support java 8
      - dependency-name: "jakarta.enterprise:jakarta.enterprise.cdi-api"
        versions:
          - ">=4.0.0" # does not support java 8
      - dependency-name: "jakarta.persistence:jakarta.persistence-api"
        versions:
          - ">3.0.0" # does not support java 8
      - dependency-name: "jakarta.servlet:jakarta.servlet-api"
        versions:
          - ">=5.0.0" # does not provide javax.servlet package necessary for pax-web 8.x
      - dependency-name: "javax.enterprise:cdi-api"
        versions:
          - ">2.0.SP1" # 2.0-PFD2 is considered as newer, but is older
      - dependency-name: "org.apache.derby:derby"
        versions:
          - ">=10.15.0" # does not support java 8
      - dependency-name: "org.apache.felix:maven-bundle-plugin"
        versions:
          - ">=6.0.0" # does not support java 8
      - dependency-name: "org.apache.geronimo.components:geronimo-connector"
        versions:
          - ">=4.0.0" # does not support java 8
      - dependency-name: "org.apache.groovy:groovy-xml"
        versions:
          - ">=5.0.0" # does not support java 8
      - dependency-name: "org.apache.openjpa:openjpa"
        versions:
          - ">=4.0.0" # does not support java 8
      - dependency-name: "org.apache.servicemix.bundles:org.apache.servicemix.bundles.spring-*"
        versions:
          - ">=6.0.0" # does not support java 8
      - dependency-name: "org.codehaus.plexus:plexus-xml*"
        versions:
          - ">=4.1.0" # does not support java 8
      - dependency-name: "org.junit.jupiter:junit-jupiter-*"
        versions:
          - ">=6.0.0" # does not support java 8
      - dependency-name: "org.junit.platform:junit-platform-*"
        versions:
          - ">=6.0.0" # does not support java 8
      - dependency-name: "org.mockito:mockito*"
        versions:
          - ">=5.0.0" # does not support java 8
      - dependency-name: "org.ops4j.pax.cdi:pax-cdi*"
        versions:
          - ">=1.0.0" # pax-cdi is only used in blueprint maven plugin as an optional annotation provider and it's changed in version 1.x in incompatible way - blueprint-maven-plugin-annotation should be used instead since provides annotations more focused on blueprint elements
      - dependency-name: "org.ops4j.pax.exam:pax-exam*"
        versions:
          - ">=4.14.0" # does not support java 8
      - dependency-name: "org.ops4j.pax.logging:pax-logging*"
        versions:
          - ">=2.3.0" # does not support java 8
      - dependency-name: "org.ops4j.pax.tinybundles:tinybundles*"
        versions:
          # 4.x changes in incompatible way, needs pax-exam >= 4.14.x
          # 3.x cannot be used by pax-exam 4.13.5
          - ">=3.0.0"
      - dependency-name: "org.ops4j.pax.url:pax-url*"
        versions:
          - ">=3.0.0" # does not support java 8
      - dependency-name: "org.ops4j.pax.web:pax-web*"
        versions:
          - ">=9.0.0" # does not support java 8
      - dependency-name: "org.ops4j.pax.swissbox:pax-swissbox*"
        versions:
          - ">1.8.3" # 1.9.0 does not support java 8, but 1.8.4 has SLF4j dependency which cannot be met https://github.com/ops4j/org.ops4j.pax.exam/issues/1056
      - dependency-name: "org.springframework:spring-*"
        versions:
          - ">=6.0.0" # does not support java 8
