<?xml version="1.0" encoding="UTF-8"?>
<!--
 Licensed to the Apache Software Foundation (ASF) under one
 or more contributor license agreements.  See the NOTICE file
 distributed with this work for additional information
 regarding copyright ownership.  The ASF licenses this file
 to you under the Apache License, Version 2.0 (the
 "License"); you may not use this file except in compliance
 with the License.  You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

 Unless required by applicable law or agreed to in writing,
 software distributed under the License is distributed on an
 "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
 KIND, either express or implied.  See the License for the
 specific language governing permissions and limitations
 under the License.
-->
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/maven-v4_0_0.xsd">

    <modelVersion>4.0.0</modelVersion>

    <parent>
        <groupId>org.apache.aries</groupId>
        <artifactId>parent</artifactId>
        <version>3.0.0</version>
        <relativePath>../../parent/pom.xml</relativePath>
    </parent>

    <groupId>org.apache.aries.transaction</groupId>
    <artifactId>org.apache.aries.transaction.itests</artifactId>
    <name>Apache Aries Transaction Integration Tests</name>
    <version>2.0.0-SNAPSHOT</version>

    <scm>
        <connection>scm:git:https://gitbox.apache.org/repos/asf/aries.git</connection>
        <developerConnection>scm:git:https://gitbox.apache.org/repos/asf/aries.git</developerConnection>
        <url>https://gitbox.apache.org/repos/asf?p=aries.git;a=summary</url>
    </scm>

    <properties>
        <jakarta.enterprise.cdi-api.version>4.0.1</jakarta.enterprise.cdi-api.version>
        <depends-maven-plugin.version>1.5.0</depends-maven-plugin.version>
        <geronimo-connector.version>4.0.0</geronimo-connector.version>
        <jakarta.resource-api.version>2.1.0</jakarta.resource-api.version>
        <jakarta.validation-api.version>3.0.2</jakarta.validation-api.version>
        <jakarta.el-api.version>5.0.1</jakarta.el-api.version>
        <jakarta.inject-api.version>2.0.1</jakarta.inject-api.version>
        <jakarta.interceptor-api.version>2.1.0</jakarta.interceptor-api.version>
        <jakarta.transaction-api.version>2.0.1</jakarta.transaction-api.version>
        <javax.inject.version>1</javax.inject.version>
        <org.apache.aries.blueprint.api.version>1.0.0</org.apache.aries.blueprint.api.version>
        <org.apache.aries.blueprint.core.version>1.4.4</org.apache.aries.blueprint.core.version>
        <org.apache.aries.proxy.impl.version>1.0.6</org.apache.aries.proxy.impl.version>
        <org.apache.aries.testsupport.unit.version>2.0.0-SNAPSHOT</org.apache.aries.testsupport.unit.version>
        <org.apache.aries.transaction.blueprint.version>3.0.0-SNAPSHOT</org.apache.aries.transaction.blueprint.version>
        <org.apache.aries.transaction.jdbc.version>3.0.0-SNAPSHOT</org.apache.aries.transaction.jdbc.version>
        <org.apache.aries.transaction.manager.version>2.0.0-SNAPSHOT</org.apache.aries.transaction.manager.version>
        <org.apache.aries.transaction.testbundle.version>2.0.0-SNAPSHOT</org.apache.aries.transaction.testbundle.version>
        <org.apache.aries.transaction.testds.version>2.0.0-SNAPSHOT</org.apache.aries.transaction.testds.version>
        <org.apache.aries.util.version>1.1.3</org.apache.aries.util.version>
        <org.apache.felix.configadmin.version>1.9.26</org.apache.felix.configadmin.version>
        <org.apache.felix.coordinator.version>1.0.2</org.apache.felix.coordinator.version>
        <org.apache.felix.scr.version>2.2.14</org.apache.felix.scr.version>
        <org.apache.servicemix.bundles.javax-inject.version>1_3</org.apache.servicemix.bundles.javax-inject.version>
        <org.eclipse.osgi.version>3.24.0</org.eclipse.osgi.version>
        <osgi.core.version>8.0.0</osgi.core.version>
        <pax-swissbox.version>1.9.0</pax-swissbox.version>
        <pax-exam.version>4.14.0</pax-exam.version>
        <pax-logging.version>2.3.1</pax-logging.version>
        <pax-tinybundles.version>4.0.1</pax-tinybundles.version>
        <bndlib.version>6.4.0</bndlib.version>
        <pax-url.version>2.6.17</pax-url.version>
        <slf4j-api.version>1.7.7</slf4j-api.version>
    </properties>

    <dependencies>
        <dependency>
            <groupId>org.eclipse.platform</groupId>
            <artifactId>org.eclipse.osgi</artifactId>
            <version>${org.eclipse.osgi.version}</version>
        </dependency>
        <dependency>
            <groupId>org.osgi</groupId>
            <artifactId>osgi.core</artifactId>
            <version>${osgi.core.version}</version>
        </dependency>
        <dependency>
            <groupId>org.apache.aries.proxy</groupId>
            <artifactId>org.apache.aries.proxy.impl</artifactId>
            <scope>test</scope>
            <version>${org.apache.aries.proxy.impl.version}</version>
        </dependency>
        <dependency>
            <groupId>org.apache.felix</groupId>
            <artifactId>org.apache.felix.coordinator</artifactId>
            <version>${org.apache.felix.coordinator.version}</version>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>org.apache.felix</groupId>
            <artifactId>org.apache.felix.configadmin</artifactId>
            <version>${org.apache.felix.configadmin.version}</version>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>org.apache.aries.blueprint</groupId>
            <artifactId>org.apache.aries.blueprint.api</artifactId>
            <version>${org.apache.aries.blueprint.api.version}</version>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>org.apache.aries.blueprint</groupId>
            <artifactId>org.apache.aries.blueprint.core</artifactId>
            <version>${org.apache.aries.blueprint.core.version}</version>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>jakarta.resource</groupId>
            <artifactId>jakarta.resource-api</artifactId>
            <version>${jakarta.resource-api.version}</version>
        </dependency>
        <dependency>
            <groupId>jakarta.validation</groupId>
            <artifactId>jakarta.validation-api</artifactId>
            <version>${jakarta.validation-api.version}</version>
        </dependency>
        <dependency>
            <groupId>org.apache.geronimo.components</groupId>
            <artifactId>geronimo-connector</artifactId>
            <version>${geronimo-connector.version}</version>
        </dependency>

        <!--  Jakarta Transaction 2.0 -->
        <dependency>
            <groupId>jakarta.transaction</groupId>
            <artifactId>jakarta.transaction-api</artifactId>
            <version>${jakarta.transaction-api.version}</version>
        </dependency>
        <dependency>
            <groupId>jakarta.interceptor</groupId>
            <artifactId>jakarta.interceptor-api</artifactId>
            <version>${jakarta.interceptor-api.version}</version>
        </dependency>
        <dependency>
            <groupId>jakarta.inject</groupId>
            <artifactId>jakarta.inject-api</artifactId>
            <version>${jakarta.inject-api.version}</version>
        </dependency>
        <dependency>
            <groupId>javax.inject</groupId>
            <artifactId>javax.inject</artifactId>
            <version>${javax.inject.version}</version>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>jakarta.el</groupId>
            <artifactId>jakarta.el-api</artifactId>
            <version>${jakarta.el-api.version}</version>
        </dependency>
        <dependency>
            <groupId>jakarta.enterprise</groupId>
            <artifactId>jakarta.enterprise.cdi-api</artifactId>
            <version>${jakarta.enterprise.cdi-api.version}</version>
        </dependency>

        <dependency>
            <groupId>org.apache.aries.transaction</groupId>
            <artifactId>org.apache.aries.transaction.manager</artifactId>
            <scope>test</scope>
            <version>${org.apache.aries.transaction.manager.version}</version>
        </dependency>
        <dependency>
            <groupId>org.apache.aries.transaction</groupId>
            <artifactId>org.apache.aries.transaction.blueprint</artifactId>
            <scope>test</scope>
            <version>${org.apache.aries.transaction.blueprint.version}</version>
        </dependency>
        <dependency>
            <groupId>org.apache.aries.transaction</groupId>
            <artifactId>org.apache.aries.transaction.jdbc</artifactId>
            <scope>test</scope>
            <version>${org.apache.aries.transaction.jdbc.version}</version>
        </dependency>
        <dependency>
            <groupId>org.apache.aries.transaction</groupId>
            <artifactId>org.apache.aries.transaction.testds</artifactId>
            <scope>test</scope>
            <version>${org.apache.aries.transaction.testds.version}</version>
        </dependency>
        <dependency>
            <groupId>org.apache.aries.transaction</groupId>
            <artifactId>org.apache.aries.transaction.testbundle</artifactId>
            <scope>test</scope>
            <version>${org.apache.aries.transaction.testbundle.version}</version>
        </dependency>
        <dependency>
            <groupId>org.apache.aries.testsupport</groupId>
            <artifactId>org.apache.aries.testsupport.unit</artifactId>
            <version>${org.apache.aries.testsupport.unit.version}</version>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>org.apache.aries</groupId>
            <artifactId>org.apache.aries.util</artifactId>
            <version>${org.apache.aries.util.version}</version>
            <scope>test</scope>
        </dependency>

        <dependency>
            <groupId>org.ops4j.pax.logging</groupId>
            <artifactId>pax-logging-api</artifactId>
            <version>${pax-logging.version}</version>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>org.ops4j.pax.logging</groupId>
            <artifactId>pax-logging-log4j2</artifactId>
            <version>${pax-logging.version}</version>
            <scope>test</scope>
        </dependency>

        <!-- pax exam -->
        <dependency>
            <groupId>org.slf4j</groupId>
            <artifactId>slf4j-api</artifactId>
            <version>${slf4j-api.version}</version>
        </dependency>
        <dependency>
            <groupId>org.ops4j.pax.exam</groupId>
            <artifactId>pax-exam</artifactId>
            <version>${pax-exam.version}</version>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>org.ops4j.pax.exam</groupId>
            <artifactId>pax-exam-container-forked</artifactId>
            <version>${pax-exam.version}</version>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>org.ops4j.pax.exam</groupId>
            <artifactId>pax-exam-junit4</artifactId>
            <version>${pax-exam.version}</version>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>org.ops4j.pax.exam</groupId>
            <artifactId>pax-exam-link-mvn</artifactId>
            <version>${pax-exam.version}</version>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>org.ops4j.pax.url</groupId>
            <artifactId>pax-url-aether</artifactId>
            <version>${pax-url.version}</version>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>org.ops4j.pax.tinybundles</groupId>
            <artifactId>tinybundles</artifactId>
            <version>${pax-tinybundles.version}</version>
        </dependency>
        <dependency>
            <groupId>org.apache.felix</groupId>
            <artifactId>org.apache.felix.scr</artifactId>
            <version>${org.apache.felix.scr.version}</version>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>junit</groupId>
            <artifactId>junit</artifactId>
            <scope>test</scope>
        </dependency>
    </dependencies>

    <build>
        <plugins>
            <plugin>
                <groupId>org.apache.servicemix.tooling</groupId>
                <artifactId>depends-maven-plugin</artifactId>
                <!-- TODO ARIES-2165: remove configuration when the newest parent pom is used -->
                <version>${depends-maven-plugin.version}</version>
                <executions>
                    <execution>
                        <id>generate-depends-file</id>
                        <goals>
                            <goal>generate-depends-file</goal>
                        </goals>
                    </execution>
                </executions>
            </plugin>
        </plugins>
    </build>
</project>
