<?xml version="1.0" encoding="UTF-8"?>
<!--
 Licensed to the Apache Software Foundation (ASF) under one
 or more contributor license agreements.  See the NOTICE file
 distributed with this work for additional information
 regarding copyright ownership.  The ASF licenses this file
 to you under the Apache License, Version 2.0 (the
 "License"); you may not use this file except in compliance
 with the License.  You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

 Unless required by applicable law or agreed to in writing,
 software distributed under the License is distributed on an
 "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
 KIND, either express or implied.  See the License for the
 specific language governing permissions and limitations
 under the License.
-->
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/maven-v4_0_0.xsd">

    <modelVersion>4.0.0</modelVersion>

    <parent>
        <groupId>org.apache.aries</groupId>
        <artifactId>parent</artifactId>
        <version>3.0.1-SNAPSHOT</version>
        <relativePath>../parent/pom.xml</relativePath>
    </parent>

    <groupId>org.apache.aries.samples</groupId>
    <version>1.0.1-SNAPSHOT</version>
    <artifactId>samples</artifactId>
    <name>Apache Aries Samples</name>
    <packaging>pom</packaging>

    <scm>
        <connection>scm:git:https://gitbox.apache.org/repos/asf/aries.git</connection>
        <developerConnection>scm:git:https://gitbox.apache.org/repos/asf/aries.git</developerConnection>
        <url>https://gitbox.apache.org/repos/asf?p=aries.git;a=summary</url>
    </scm>

    <!-- VERSIONS - PLEASE NOTE 
         All version information for the samples is maintained in this pom. The versions are used by submodules automatically 
         AND are referred to in 'filtered-resources' for each project when building (eg) assemblies. 
     -->

    <properties>
        <!-- Aries Blueprint Versions -->
        <org.apache.aries.blueprint.version>1.1.0</org.apache.aries.blueprint.version>

        <!-- Aries Jndi Versions -->
        <org.apache.aries.jndi.version>1.0.0</org.apache.aries.jndi.version>

        <!-- Aries Jpa Versions -->
        <org.apache.aries.jpa.api.version>1.0.2</org.apache.aries.jpa.api.version>
        <org.apache.aries.jpa.blueprint.aries.version>1.0.4</org.apache.aries.jpa.blueprint.aries.version>
        <org.apache.aries.jpa.container.version>1.0.4</org.apache.aries.jpa.container.version>
        <org.apache.aries.jpa.container.context.version>1.0.4</org.apache.aries.jpa.container.context.version>

        <!-- Aries Quiesce Versions -->
        <org.apache.aries.quiesce.api.version>1.0.0</org.apache.aries.quiesce.api.version>
        <org.apache.aries.quiesce.manager.version>1.0.0</org.apache.aries.quiesce.manager.version>

        <!-- Aries Testsupport Versions -->
        <org.apache.aries.testsupport.unit.version>2.0.0-SNAPSHOT</org.apache.aries.testsupport.unit.version>

        <!-- Aries Transaction Versions -->
        <org.apache.aries.transaction.blueprint.version>1.0.0</org.apache.aries.transaction.blueprint.version>
        <org.apache.aries.transaction.manager.version>1.0.0</org.apache.aries.transaction.manager.version>
        <org.apache.aries.transaction.wrappers.version>1.0.0</org.apache.aries.transaction.wrappers.version>

        <!-- External Dependencies -->
        <cm.version>3.2.0-v20070116</cm.version>
        <services.version>3.1.200-v20070605</services.version>
        <derby.version>10.14.2.0</derby.version>
        <commons-collections.version>3.2.2</commons-collections.version>
        <commons-lang.version>2.6</commons-lang.version>
        <commons-pool.version>1.6</commons-pool.version>
        <org.apache.servicemix.bundles.serp.version>1.15.1_1</org.apache.servicemix.bundles.serp.version>
        <org.eclipse.osgi.version>3.23.100</org.eclipse.osgi.version>

        <openjpa.version>2.2.2</openjpa.version>
        <geronimo-jpa_2.0_spec.version>1.1</geronimo-jpa_2.0_spec.version>
        <geronimo-jta_1.1_spec.version>1.1.1</geronimo-jta_1.1_spec.version>
        <geronimo-transaction.version>2.1.3</geronimo-transaction.version>
        <geronimo-servlet_2.5_spec.version>1.2</geronimo-servlet_2.5_spec.version>
        <geronimo-j2ee-connector_1.5_spec.version>2.0.0</geronimo-j2ee-connector_1.5_spec.version>
        <geronimo-jsp_2.1_spec.version>1.0.1</geronimo-jsp_2.1_spec.version>

        <pax-web.version>8.0.32</pax-web.version>

        <org.apache.felix.fileinstall.version>3.7.4</org.apache.felix.fileinstall.version>
        <serp.version>1.15.1</serp.version>
        <javax-servlet.version>1.2</javax-servlet.version>

        <aries.javadoc.exclude.packages>*</aries.javadoc.exclude.packages>

        <!-- Felix dependencies -->
        <jansi.version>2.4.2</jansi.version>
        <jline.version>3.30.6</jline.version>
        <org.apache.felix.bundlerepository.version>2.0.10</org.apache.felix.bundlerepository.version>
        <org.apache.felix.configadmin.version>1.9.26</org.apache.felix.configadmin.version>
        <org.apache.felix.eventadmin.version>1.6.4</org.apache.felix.eventadmin.version>
        <org.apache.felix.gogo.command.version>1.1.2</org.apache.felix.gogo.command.version>
        <org.apache.felix.gogo.jline.version>1.1.8</org.apache.felix.gogo.jline.version>
        <org.apache.felix.gogo.runtime.version>1.1.6</org.apache.felix.gogo.runtime.version>
        <org.apache.felix.main.version>7.0.5</org.apache.felix.main.version>

        <!-- Aries bundle dependencies-->
        <asm.version>9.8</asm.version>
        <javax.annotation-api.version>1.3.2</javax.annotation-api.version>
        <javax.inject.version>1</javax.inject.version>
        <javax.persistence-api.version>2.2</javax.persistence-api.version>
        <javax.transaction-api.version>1.2</javax.transaction-api.version>
        <osgi.core.version>8.0.0</osgi.core.version>
        <pax-logging.version>2.2.9</pax-logging.version>

        <!-- Aries dependencies -->
        <blueprint-maven-plugin-annotation.version>1.3.0</blueprint-maven-plugin-annotation.version>
        <blueprint-maven-plugin.version>1.10.0</blueprint-maven-plugin.version>
        <org.apache.aries.blueprint.api.version>1.0.1</org.apache.aries.blueprint.api.version>
        <org.apache.aries.blueprint.cm.version>1.3.2</org.apache.aries.blueprint.cm.version>
        <org.apache.aries.blueprint.core.version>1.10.3</org.apache.aries.blueprint.core.version>
        <org.apache.aries.proxy.version>1.1.14</org.apache.aries.proxy.version>
        <org.apache.aries.util.version>1.1.3</org.apache.aries.util.version>
    </properties>

    <dependencyManagement>
        <dependencies>
            <!-- External project dependencies -->
            <dependency>
                <groupId>org.osgi</groupId>
                <artifactId>osgi.core</artifactId>
                <version>${osgi.core.version}</version>
                <scope>provided</scope>
            </dependency>
            <dependency>
                <groupId>org.apache.felix</groupId>
                <artifactId>org.apache.felix.main</artifactId>
                <version>${org.apache.felix.main.version}</version>
            </dependency>
            <dependency>
                <groupId>org.fusesource.jansi</groupId>
                <artifactId>jansi</artifactId>
                <version>${jansi.version}</version>
            </dependency>
            <dependency>
                <groupId>org.jline</groupId>
                <artifactId>jline</artifactId>
                <version>${jline.version}</version>
            </dependency>
            <dependency>
                <groupId>org.apache.felix</groupId>
                <artifactId>org.apache.felix.bundlerepository</artifactId>
                <version>${org.apache.felix.bundlerepository.version}</version>
            </dependency>
            <dependency>
                <groupId>org.apache.felix</groupId>
                <artifactId>org.apache.felix.gogo.command</artifactId>
                <version>${org.apache.felix.gogo.command.version}</version>
            </dependency>
            <dependency>
                <groupId>org.apache.felix</groupId>
                <artifactId>org.apache.felix.gogo.jline</artifactId>
                <version>${org.apache.felix.gogo.jline.version}</version>
            </dependency>
            <dependency>
                <groupId>org.apache.felix</groupId>
                <artifactId>org.apache.felix.gogo.runtime</artifactId>
                <version>${org.apache.felix.gogo.runtime.version}</version>
            </dependency>

            <dependency>
                <groupId>org.ow2.asm</groupId>
                <artifactId>asm</artifactId>
                <version>${asm.version}</version>
                <scope>provided</scope>
            </dependency>
            <dependency>
                <groupId>org.ow2.asm</groupId>
                <artifactId>asm-commons</artifactId>
                <version>${asm.version}</version>
                <scope>provided</scope>
            </dependency>
            <dependency>
                <groupId>org.ow2.asm</groupId>
                <artifactId>asm-tree</artifactId>
                <version>${asm.version}</version>
                <scope>provided</scope>
            </dependency>
            <dependency>
                <groupId>org.ow2.asm</groupId>
                <artifactId>asm-analysis</artifactId>
                <version>${asm.version}</version>
                <scope>provided</scope>
            </dependency>

            <dependency>
                <groupId>org.apache.felix</groupId>
                <artifactId>org.apache.felix.configadmin</artifactId>
                <version>${org.apache.felix.configadmin.version}</version>
            </dependency>

            <dependency>
                <groupId>org.apache.felix</groupId>
                <artifactId>org.apache.felix.eventadmin</artifactId>
                <version>${org.apache.felix.eventadmin.version}</version>
            </dependency>

            <dependency>
                <groupId>org.ops4j.pax.web</groupId>
                <artifactId>pax-web-extender-war</artifactId>
                <version>${pax-web.version}</version>
            </dependency>
            <dependency>
                <groupId>org.ops4j.pax.web</groupId>
                <artifactId>pax-web-jetty-bundle</artifactId>
                <version>${pax-web.version}</version>
            </dependency>
            <dependency>
                <groupId>org.ops4j.pax.web</groupId>
                <artifactId>pax-web-jsp</artifactId>
                <version>${pax-web.version}</version>
            </dependency>
            <dependency>
                <groupId>org.apache.geronimo.specs</groupId>
                <artifactId>geronimo-j2ee-connector_1.5_spec</artifactId>
                <version>${geronimo-j2ee-connector_1.5_spec.version}</version>
            </dependency>
            <dependency>
                <groupId>org.apache.geronimo.specs</groupId>
                <artifactId>geronimo-servlet_2.5_spec</artifactId>
                <version>${geronimo-servlet_2.5_spec.version}</version>
            </dependency>
            <dependency>
                <groupId>org.apache.geronimo.specs</groupId>
                <artifactId>geronimo-jsp_2.1_spec</artifactId>
                <version>${geronimo-jsp_2.1_spec.version}</version>
            </dependency>
            <dependency>
                <groupId>org.apache.geronimo.components</groupId>
                <artifactId>geronimo-transaction</artifactId>
                <version>${geronimo-transaction.version}</version>
            </dependency>
            <dependency>
                <groupId>org.apache.geronimo.specs</groupId>
                <artifactId>geronimo-jta_1.1_spec</artifactId>
                <version>${geronimo-jta_1.1_spec.version}</version>
            </dependency>
            <dependency>
                <groupId>org.apache.geronimo.specs</groupId>
                <artifactId>geronimo-jpa_2.0_spec</artifactId>
                <version>${geronimo-jpa_2.0_spec.version}</version>
            </dependency>
            <dependency>
                <groupId>org.apache.derby</groupId>
                <artifactId>derby</artifactId>
                <version>${derby.version}</version>
            </dependency>
            <dependency>
                <groupId>org.apache.openjpa</groupId>
                <artifactId>openjpa</artifactId>
                <version>${openjpa.version}</version>
            </dependency>
            <dependency>
                <groupId>net.sourceforge.serp</groupId>
                <artifactId>serp</artifactId>
                <version>${serp.version}</version>
            </dependency>
            <!-- bundle version of serp necessary for equinox assembly using openjpa -->
            <dependency>
                <groupId>org.apache.servicemix.bundles</groupId>
                <artifactId>org.apache.servicemix.bundles.serp</artifactId>
                <version>${org.apache.servicemix.bundles.serp.version}</version>
            </dependency>
            <dependency>
                <groupId>commons-lang</groupId>
                <artifactId>commons-lang</artifactId>
                <version>${commons-lang.version}</version>
            </dependency>
            <dependency>
                <groupId>commons-pool</groupId>
                <artifactId>commons-pool</artifactId>
                <version>${commons-pool.version}</version>
            </dependency>
            <dependency>
                <groupId>commons-collections</groupId>
                <artifactId>commons-collections</artifactId>
                <version>${commons-collections.version}</version>
            </dependency>
            <dependency>
                <groupId>org.apache.felix</groupId>
                <artifactId>org.apache.felix.fileinstall</artifactId>
                <version>${org.apache.felix.fileinstall.version}</version>
            </dependency>

            <!-- other aries subproject dependency management -->
            <!-- blueprint -->
            <dependency>
                <groupId>org.apache.aries.blueprint</groupId>
                <artifactId>org.apache.aries.blueprint.api</artifactId>
                <version>${org.apache.aries.blueprint.api.version}</version>
            </dependency>
            <dependency>
                <groupId>org.apache.aries.blueprint</groupId>
                <artifactId>org.apache.aries.blueprint</artifactId>
                <version>${org.apache.aries.blueprint.version}</version>
            </dependency>
            <dependency>
                <groupId>org.apache.aries.blueprint</groupId>
                <artifactId>org.apache.aries.blueprint.cm</artifactId>
                <version>${org.apache.aries.blueprint.cm.version}</version>
            </dependency>
            <dependency>
                <groupId>org.apache.aries.blueprint</groupId>
                <artifactId>org.apache.aries.blueprint.core</artifactId>
                <version>${org.apache.aries.blueprint.core.version}</version>
            </dependency>
            <!-- jndi -->
            <dependency>
                <groupId>org.apache.aries.jndi</groupId>
                <artifactId>org.apache.aries.jndi</artifactId>
                <version>${org.apache.aries.jndi.version}</version>
            </dependency>
            <!-- jpa -->
            <dependency>
                <groupId>org.apache.aries.jpa</groupId>
                <artifactId>org.apache.aries.jpa.api</artifactId>
                <version>${org.apache.aries.jpa.api.version}</version>
            </dependency>
            <dependency>
                <groupId>org.apache.aries.jpa</groupId>
                <artifactId>org.apache.aries.jpa.blueprint.aries</artifactId>
                <version>${org.apache.aries.jpa.blueprint.aries.version}</version>
            </dependency>
            <dependency>
                <groupId>org.apache.aries.jpa</groupId>
                <artifactId>org.apache.aries.jpa.container</artifactId>
                <version>${org.apache.aries.jpa.container.version}</version>
            </dependency>
            <dependency>
                <groupId>org.apache.aries.jpa</groupId>
                <artifactId>org.apache.aries.jpa.container.context</artifactId>
                <version>${org.apache.aries.jpa.container.context.version}</version>
            </dependency>
            <!-- proxy -->
            <dependency>
                <groupId>org.apache.aries.proxy</groupId>
                <artifactId>org.apache.aries.proxy</artifactId>
                <version>${org.apache.aries.proxy.version}</version>
            </dependency>
            <!-- quiesce -->
            <dependency>
                <groupId>org.apache.aries.quiesce</groupId>
                <artifactId>org.apache.aries.quiesce.api</artifactId>
                <version>${org.apache.aries.quiesce.api.version}</version>
            </dependency>
            <dependency>
                <groupId>org.apache.aries.quiesce</groupId>
                <artifactId>org.apache.aries.quiesce.manager</artifactId>
                <version>${org.apache.aries.quiesce.manager.version}</version>
            </dependency>
            <!-- Testsupport -->
            <dependency>
                <groupId>org.apache.aries.testsupport</groupId>
                <artifactId>org.apache.aries.testsupport.unit</artifactId>
                <version>${org.apache.aries.testsupport.unit.version}</version>
            </dependency>
            <!-- transaction -->
            <dependency>
                <groupId>org.apache.aries.transaction</groupId>
                <artifactId>org.apache.aries.transaction.blueprint</artifactId>
                <version>${org.apache.aries.transaction.blueprint.version}</version>
            </dependency>
            <dependency>
                <groupId>org.apache.aries.transaction</groupId>
                <artifactId>org.apache.aries.transaction.manager</artifactId>
                <version>${org.apache.aries.transaction.manager.version}</version>
            </dependency>
            <dependency>
                <groupId>org.apache.aries.transaction</groupId>
                <artifactId>org.apache.aries.transaction.wrappers</artifactId>
                <version>${org.apache.aries.transaction.wrappers.version}</version>
            </dependency>
            <!--util-->
            <dependency>
                <groupId>org.apache.aries</groupId>
                <artifactId>org.apache.aries.util</artifactId>
                <version>${org.apache.aries.util.version}</version>
            </dependency>

            <dependency>
                <groupId>org.apache.aries.blueprint</groupId>
                <artifactId>blueprint-maven-plugin-annotation</artifactId>
                <version>${blueprint-maven-plugin-annotation.version}</version>
                <scope>provided</scope>
            </dependency>
            <dependency>
                <groupId>javax.inject</groupId>
                <artifactId>javax.inject</artifactId>
                <version>${javax.inject.version}</version>
                <scope>provided</scope>
            </dependency>
            <dependency>
                <groupId>javax.transaction</groupId>
                <artifactId>javax.transaction-api</artifactId>
                <version>${javax.transaction-api.version}</version>
                <scope>provided</scope>
            </dependency>
            <dependency>
                <groupId>javax.persistence</groupId>
                <artifactId>javax.persistence-api</artifactId>
                <version>${javax.persistence-api.version}</version>
                <scope>provided</scope>
            </dependency>
            <dependency>
                <groupId>javax.annotation</groupId>
                <artifactId>javax.annotation-api</artifactId>
                <version>${javax.annotation-api.version}</version>
                <scope>provided</scope>
            </dependency>

            <dependency>
                <groupId>org.eclipse.platform</groupId>
                <artifactId>org.eclipse.osgi</artifactId>
                <version>${org.eclipse.osgi.version}</version>
            </dependency>
        </dependencies>
    </dependencyManagement>

    <build>
        <pluginManagement>
            <plugins>
                <plugin>
                    <groupId>org.apache.aries.blueprint</groupId>
                    <artifactId>blueprint-maven-plugin</artifactId>
                    <version>${blueprint-maven-plugin.version}</version>
                    <executions>
                        <execution>
                            <phase>process-classes</phase>
                            <goals>
                                <goal>add-resource-dir</goal>
                                <goal>blueprint-generate</goal>
                            </goals>
                        </execution>
                    </executions>
                </plugin>
            </plugins>
        </pluginManagement>
    </build>

    <modules>
        <module>ariestrader</module>
        <module>blog</module>
        <module>blueprint</module>
    </modules>

</project>
