# Licensed to the Apache Software Foundation (ASF) under one
# or more contributor license agreements.  See the NOTICE file
# distributed with this work for additional information
# regarding copyright ownership.  The ASF licenses this file
# to you under the Apache License, Version 2.0 (the
# "License"); you may not use this file except in compliance
# with the License.  You may obtain a copy of the License at
#
#  http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing,
# software distributed under the License is distributed on an
# "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
# KIND, either express or implied.  See the License for the
# specific language governing permissions and limitations
# under the License.

osgi.bundles=\
cm-${cm.version}.jar@start,\
services-${services.version}.jar@start,\
asm-${asm.version}.jar@start,\
asm-commons-${asm.version}.jar@start,\
asm-tree-${asm.version}.jar@start,\
asm-analysis-${asm.version}.jar@start,\
pax-logging-api-${pax-logging.version}.jar@start,\
pax-logging-service-${pax-logging.version}.jar@start,\
derby-${derby.version}.jar@start,\
commons-collections-${commons-collections.version}.jar@start,\
commons-lang-${commons-lang.version}.jar@start,\
commons-pool-${commons-pool.version}.jar@start,\
org.apache.servicemix.bundles.serp-${org.apache.servicemix.bundles.serp.version}.jar@start,\
openjpa-${openjpa.version}.jar@start,\
geronimo-j2ee-connector_1.5_spec-${geronimo-j2ee-connector_1.5_spec.version}.jar@start,\
geronimo-jpa_2.0_spec-${geronimo-jpa_2.0_spec.version}.jar@start,\
geronimo-jta_1.1_spec-${geronimo-jta_1.1_spec.version}.jar@start,\
geronimo-transaction-${geronimo-transaction.version}.jar@start,\
geronimo-servlet_2.5_spec-${geronimo-servlet_2.5_spec.version}.jar@start,\
pax-web-jetty-bundle-${pax-web.version}.jar@start,\
pax-web-extender-war-${pax-web.version}.jar@start,\
pax-web-jsp-${pax-web.version}.jar@start,\
org.apache.felix.fileinstall-${org.apache.felix.fileinstall.version}.jar@start,\
org.apache.felix.bundlerepository-${org.apache.felix.bundlerepository.version}.jar@start,\
org.apache.aries.application.install-${org.apache.aries.application.install.version}.jar@start,\
org.apache.aries.application.management-${org.apache.aries.application.management.version}.jar@start,\
org.apache.aries.application.api-${org.apache.aries.application.api.version}.jar@start,\
org.apache.aries.application.utils-${org.apache.aries.application.utils.version}.jar@start,\
org.apache.aries.application.runtime-${org.apache.aries.application.runtime.version}.jar@start,\
org.apache.aries.application.deployment.management-${org.apache.aries.application.deployment.management.version}.jar@start,\
org.apache.aries.application.modeller-${org.apache.aries.application.modeller.version}.jar@start,\
org.apache.aries.application.resolver.obr-${org.apache.aries.application.resolver.obr.version}.jar@start,\
org.apache.aries.application.resolver.noop-${org.apache.aries.application.resolver.noop.version}.jar@start,\
org.apache.aries.application.default.local.platform-${org.apache.aries.application.default.local.platform.version}.jar@start,\
org.apache.aries.jndi-${org.apache.aries.jndi.version}.jar@start,\
org.apache.aries.jpa.api-${org.apache.aries.jpa.api.version}.jar@start,\
org.apache.aries.jpa.blueprint.aries-${org.apache.aries.jpa.blueprint.aries.version}.jar@start,\
org.apache.aries.jpa.container-${org.apache.aries.jpa.container.version}.jar@start,\
org.apache.aries.jpa.container.context-${org.apache.aries.jpa.container.context.version}.jar@start,\
org.apache.aries.util-${org.apache.aries.util.version}.jar@start,\
org.apache.aries.blueprint-${org.apache.aries.blueprint.version}.jar@start,\
org.apache.aries.proxy-${org.apache.aries.proxy.version}.jar@start,\
org.apache.aries.transaction.blueprint-${org.apache.aries.transaction.blueprint.version}.jar@start,\
org.apache.aries.transaction.manager-${org.apache.aries.transaction.manager.version}.jar@start,\
org.apache.aries.transaction.wrappers-${org.apache.aries.transaction.wrappers.version}.jar@start,\
org.apache.aries.samples.ariestrader.derby.ds-${project.version}.jar@start
eclipse.ignoreApp=true
org.ops4j.pax.logging.DefaultServiceLog.level=DEBUG
org.osgi.framework.system.packages=\
javax.accessibility,\
javax.activation,\
javax.activity,\
javax.annotation,\
javax.annotation.processing,\
javax.crypto,\
javax.crypto.interfaces,\
javax.crypto.spec,\
javax.imageio,\
javax.imageio.event,\
javax.imageio.metadata,\
javax.imageio.plugins.bmp,\
javax.imageio.plugins.jpeg,\
javax.imageio.spi,\
javax.imageio.stream,\
javax.jws,\
javax.jws.soap,\
javax.lang.model,\
javax.lang.model.element,\
javax.lang.model.type,\
javax.lang.model.util,\
javax.management,\
javax.management.loading,\
javax.management.modelmbean,\
javax.management.monitor,\
javax.management.openmbean,\
javax.management.relation,\
javax.management.remote,\
javax.management.remote.rmi,\
javax.management.timer,\
javax.naming,\
javax.naming.directory,\
javax.naming.event,\
javax.naming.ldap,\
javax.naming.spi,\
javax.net,\
javax.net.ssl,\
javax.print,\
javax.print.attribute,\
javax.print.attribute.standard,\
javax.print.event,javax.rmi,\
javax.rmi.CORBA,\
javax.rmi.ssl,\
javax.script,\
javax.security.auth,\
javax.security.auth.callback,\
javax.security.auth.kerberos,\
javax.security.auth.login,\
javax.security.auth.spi,\
javax.security.auth.x500,\
javax.security.cert,\
javax.security.sasl,\
javax.sound.midi,\
javax.sound.midi.spi,javax.sound.sampled,\
javax.sound.sampled.spi,\
javax.sql,\
javax.sql.rowset,\
javax.sql.rowset.serial,\
javax.sql.rowset.spi,\
javax.swing,\
javax.swing.border,\
javax.swing.colorchooser,\
javax.swing.event,\
javax.swing.filechooser,\
javax.swing.plaf,\
javax.swing.plaf.basic,\
javax.swing.plaf.metal,\
javax.swing.plaf.multi,\
javax.swing.plaf.synth,\
javax.swing.table,\
javax.swing.text,\
javax.swing.text.html,\
javax.swing.text.html.parser,\
javax.swing.text.rtf,\
javax.swing.tree,\
javax.swing.undo,\
javax.tools,\
javax.xml,\
javax.xml.bind,\
javax.xml.bind.annotation,\
javax.xml.bind.annotation.adapters,\
javax.xml.bind.attachment,\
javax.xml.bind.helpers,\
javax.xml.bind.util,\
javax.xml.crypto,\
javax.xml.crypto.dom,\
javax.xml.crypto.dsig,\
javax.xml.crypto.dsig.dom,\
javax.xml.crypto.dsig.keyinfo,\
javax.xml.crypto.dsig.spec,\
javax.xml.datatype,\
javax.xml.namespace,\
javax.xml.parsers,\
javax.xml.soap,\
javax.xml.stream,\
javax.xml.stream.events,\
javax.xml.stream.util,\
javax.xml.transform,\
javax.xml.transform.dom,\
javax.xml.transform.sax,\
javax.xml.transform.stax,\
javax.xml.transform.stream,\
javax.xml.validation,\
javax.xml.ws,\
javax.xml.ws.handler,\
javax.xml.ws.handler.soap,\
javax.xml.ws.http,\
javax.xml.ws.soap,\
javax.xml.ws.spi,\
javax.xml.xpath,\
org.ietf.jgss,\
org.omg.CORBA,\
org.omg.CORBA.DynAnyPackage,\
org.omg.CORBA.ORBPackage,\
org.omg.CORBA.TypeCodePackage,\
org.omg.CORBA.portable,\
org.omg.CORBA_2_3,\
org.omg.CORBA_2_3.portable,\
org.omg.CosNaming,\
org.omg.CosNaming.NamingContextExtPackage,\
org.omg.CosNaming.NamingContextPackage,\
org.omg.Dynamic,org.omg.DynamicAny,\
org.omg.DynamicAny.DynAnyFactoryPackage,\
org.omg.DynamicAny.DynAnyPackage,\
org.omg.IOP,\
org.omg.IOP.CodecFactoryPackage,\
org.omg.IOP.CodecPackage,\
org.omg.Messaging,\
org.omg.PortableInterceptor,\
org.omg.PortableInterceptor.ORBInitInfoPackage,\
org.omg.PortableServer,\
org.omg.PortableServer.CurrentPackage,\
org.omg.PortableServer.POAManagerPackage,\
org.omg.PortableServer.POAPackage,\
org.omg.PortableServer.ServantLocatorPackage,\
org.omg.PortableServer.portable,\
org.omg.SendingContext,\
org.omg.stub.java.rmi,\
org.w3c.dom,\
org.w3c.dom.bootstrap,\
org.w3c.dom.css,\
org.w3c.dom.events,\
org.w3c.dom.html,\
org.w3c.dom.ls,\
org.w3c.dom.ranges,\
org.w3c.dom.stylesheets,\
org.w3c.dom.traversal,\
org.w3c.dom.views,\
org.xml.sax,\
org.xml.sax.ext,\
org.xml.sax.helpers,\
javax.transaction;partial=true;mandatory:=partial,\
javax.transaction.xa;partial=true;mandatory:=partial

