################################################################################
# Copyright 2010 
# 
#  Licensed to the Apache Software Foundation (ASF) under one or more
#  contributor license agreements.  See the NOTICE file distributed with
#  this work for additional information regarding copyright ownership.
#  The ASF licenses this file to You under the Apache License, Version 2.0
#  (the "License"); you may not use this file except in compliance with
#  the License.  You may obtain a copy of the License at
#     
#     http://www.apache.org/licenses/LICENSE-2.0
#     
#  Unless required by applicable law or agreed to in writing, software
#  distributed under the License is distributed on an "AS IS" BASIS,
#  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#  See the License for the specific language governing permissions and
#  limitations under the License.
################################################################################
##############################
# Felix settings
##############################
felix.log.level=1

org.osgi.framework.startlevel.beginning=10
felix.startlevel.bundle=10

##############################
# Log setting
##############################
org.ops4j.pax.logging.DefaultServiceLog.level=INFO

##############################
# Client bundles to install
##############################
# enable gogo to have access to command line in interactive mode
felix.auto.start.1=\
"file:bundles/jansi-${jansi.version}.jar" \
"file:bundles/jline-${jline.version}.jar" \
"file:bundles/org.apache.felix.gogo.command-${org.apache.felix.gogo.command.version}.jar" \
"file:bundles/org.apache.felix.gogo.jline-${org.apache.felix.gogo.jline.version}.jar" \
"file:bundles/org.apache.felix.gogo.runtime-${org.apache.felix.gogo.runtime.version}.jar"
felix.auto.start.2=\
"file:bundles/org.apache.felix.bundlerepository-${org.apache.felix.bundlerepository.version}.jar" \
"file:bundles/pax-logging-api-${pax-logging.version}.jar" \
"file:bundles/pax-logging-log4j2-${pax-logging.version}.jar" \
"file:bundles/org.apache.felix.eventadmin-${org.apache.felix.eventadmin.version}.jar" \
"file:bundles/org.apache.felix.configadmin-${org.apache.felix.configadmin.version}.jar" \
"file:bundles/org.apache.aries.util-${org.apache.aries.util.version}.jar"
felix.auto.start.3=\
"file:bundles/asm-${asm.version}.jar" \
"file:bundles/asm-commons-${asm.version}.jar" \
"file:bundles/asm-tree-${asm.version}.jar" \
"file:bundles/asm-analysis-${asm.version}.jar" \
"file:bundles/org.apache.aries.proxy-${org.apache.aries.proxy.version}.jar" \
"file:bundles/org.apache.aries.blueprint.api-${org.apache.aries.blueprint.api.version}.jar" \
"file:bundles/org.apache.aries.blueprint.cm-${org.apache.aries.blueprint.cm.version}.jar" \
"file:bundles/org.apache.aries.blueprint.core-${org.apache.aries.blueprint.core.version}.jar"
felix.auto.start.5=\
"file:bundles/org.apache.aries.samples.blueprint.idverifier.server-${project.version}.jar" \
"file:bundles/org.apache.aries.samples.blueprint.idverifier.client-${project.version}.jar" \
"file:bundles/org.apache.aries.samples.blueprint.idverifier.api-${project.version}.jar"
